name: CD - Deployment - 10

on:
  workflow_dispatch:

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get ECS Task Definition ARN
        id: get_task_def
        run: |
          RAW_OUTPUT=$(aws ecs list-task-definitions \
            --family-prefix strapi-task \
            --sort DESC \
            --max-items 1 \
            --query 'taskDefinitionArns' \
            --output text)
      
          echo "Raw output: $RAW_OUTPUT"
      
          TASK_ARN=$(echo "$RAW_OUTPUT" | grep -v 'None' | head -n 1)
      
          if [ -z "$TASK_ARN" ]; then
            echo "No valid task definition ARN found. Exiting."
            exit 1
          fi
      
          echo "Valid task definition ARN: $TASK_ARN"
          echo "taskDefinitionArn=$TASK_ARN" >> $GITHUB_OUTPUT

      - name: Trigger CodeDeploy Deployment
        run: |
          APPSPEC_JSON=$(jq -n \
            --arg taskdef "${{ steps.get_task_def.outputs.taskDefinitionArn }}" \
            '{
              version: "1.0",
              Resources: [{
                TargetService: {
                  Type: "AWS::ECS::Service",
                  Properties: {
                    TaskDefinition: $taskdef,
                    LoadBalancerInfo: {
                      ContainerName: "strapi",
                      ContainerPort: 1337
                    }
                  }
                }
              }]
            }')

          REVISION_JSON=$(jq -n \
            --arg content "$APPSPEC_JSON" \
            '{
              revisionType: "AppSpecContent",
              appSpecContent: {
                content: $content
              }
            }')

          aws deploy create-deployment \
            --application-name strapi-app-deploy \
            --deployment-group-name strapi-deploy-group \
            --deployment-config-name CodeDeployDefault.ECSCanary10Percent5Minutes \
            --revision "$REVISION_JSON"
