name: Deploy Strapi App to ECS (Blue/Green)

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 816069168735.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: strapi-app-image

jobs:
  deploy:
    name: Build and Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:latest .
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

      - name: Initialize Terraform
        run: |
          cd terraform10
          terraform init
        
      - name: Generate Terraform Plan
        run: |
          cd terraform10
          terraform plan

      - name: Apply Terraform to deploy ECS and CodeDeploy
        run: |
          cd terraform10
          terraform apply -auto-approve -var "image_uri=${{ secrets.ECR_REPOSITORY_URI }}:latest"
      
